version: "3.8"
services:
  first:
    image: maxultrasystem/send-nodes
    container_name: first
    hostname: node1
    networks:
      - blockchain
    environment:
      NODE_ADDRESS: node1:1337
      PEER_ADDRESSES: node2:1338,node3:1339
    command: java -jar /app/send-nodes.jar
  second:
    image: maxultrasystem/send-nodes
    container_name: second
    hostname: node2
    networks:
      - blockchain
    environment:
      NODE_ADDRESS: node2:1338
      PEER_ADDRESSES: node1:1337,node3:1339
    command: java -jar /app/send-nodes.jar
  third:
    image: maxultrasystem/send-nodes
    container_name: third
    hostname: node3
    networks:
      - blockchain
    environment:
      NODE_ADDRESS: node3:1339
      PEER_ADDRESSES: node1:1337,node2:1338
    command: java -jar /app/send-nodes.jar

networks:
  blockchain:
