version: "3.8"
services:
  first:
    image: maxultrasystem/send-nodes
    container_name: first
    hostname: node1
    networks:
      - blockchain
    environment:
      NODE_ADDRESS: node1:9999
      PEER_ADDRESSES: node2,node3
    command: java -jar /app/send-nodes.jar
  second:
    image: maxultrasystem/send-nodes
    container_name: second
    hostname: node2
    networks:
      - blockchain
    environment:
      NODE_ADDRESS: node2
      PEER_ADDRESSES: node1:9999,node3
    command: java -jar /app/send-nodes.jar
  third:
    image: maxultrasystem/send-nodes
    container_name: third
    hostname: node3
    networks:
      - blockchain
    environment:
      NODE_ADDRESS: node3
      PEER_ADDRESSES: node1:9999,node2
    command: java -jar /app/send-nodes.jar

networks:
  blockchain:
